version: "3"
services:
  db:
    # image: 'mysql/mysql-server:8.0'
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: prueba
      MYSQL_DATABASE: prueba
      MYSQL_USER: prueba
      MYSQL_PASSWORD: prueba
    ports:
        - "3307:3306"
    volumes:
          - "db-data:/var/lib/mysql"
  front:
    build: ./src/ecomerce
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: prueba
      DB_USERNAME: prueba
      DB_PASSWORD: prueba
      DB_CONNECTION: mysql
    volumes:
      - "./src/ecomerce/src:/var/www"
volumes:
  db-data:
