<pv-sidebar
  v-model:visible="mobileMenuDrawer"
  location="left"
  temporary
  @update:model-value="onToggleMobileMenuDrawer"
>
  <x-nav.link-list></x-nav.link-list>
  <hr>
  <x-nav.auth-links></x-nav.auth-links>
</pv-sidebar>
