<pv-sidebar
  v-model:visible="mobile_menu_drawer"
  location="left"
  temporary
  @update:model-value="toggle_mobile_menu_drawer"
>
  <x-nav.link-list></x-nav.link-list>
  <hr>
  <x-nav.auth-links></x-nav.auth-links>
</pv-sidebar>
